auto: true
highlighter: pygments
pygments: true
permalink: /:title
encoding: utf-8
title: BeiYuu.com
url: http://liwei-ch.github.io
feed: /atom.xml
author_info: <a href="http://liwei-ch.github.io/">liwei-ch</a>

defaults:
-
  scope:
      path: "" # an empty string here means all files in the project
  values:
      layout: ""
-
  scope:
       path: "blog"
  values:
       layout: "blog"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
